import { ArrowLeft, CheckCircle2, RotateCcw, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useProfiles } from '../app/providers/ProfileProvider';
import { useStudyRepository } from '../app/providers/RepositoryProvider';
import { topicById } from '../content/topics';
import type { QuizAnswer } from '../features/quizzes/scoreQuiz';
import { isAnswerCorrect } from '../features/quizzes/scoreQuiz';
import { createInitialQuizAnswers } from '../features/quizzes/createInitialAnswers';
import { QuizQuestionView } from '../features/quizzes/QuizQuestionView';
import { Button, LinkButton } from '../shared/ui/Button';
import { createId } from '../shared/utils/id';

export function QuizPage(){const{topicId}=useParams();const topic=topicId?topicById.get(topicId):undefined;const{activeProfileId}=useProfiles();const{repository,notifyDataChanged}=useStudyRepository();const[answers,setAnswers]=useState<Record<string,QuizAnswer>>(()=>createInitialQuizAnswers(topic?.quiz??[]));const[result,setResult]=useState<{correct:number;total:number}|null>(null);useEffect(()=>{setAnswers(createInitialQuizAnswers(topic?.quiz??[]));setResult(null)},[topic]);if(!topic)return <div className="empty-state"><h1>Тема не найдена</h1></div>;const submit=async()=>{const correct=topic.quiz.filter((q)=>isAnswerCorrect(q,answers[q.id])).length;const total=topic.quiz.length;setResult({correct,total});if(activeProfileId){const now=new Date().toISOString();await repository.saveQuizAttempt({id:createId('quiz'),profileId:activeProfileId,topicId:topic.id,correct,total,score:correct/total,answers,completedAt:now,updatedAt:now});const current=await repository.getTopicProgress(activeProfileId,topic.id);await repository.saveTopicProgress(current?{...current,status:correct/total<0.5?'needs-review':current.status,updatedAt:now}:{id:`${activeProfileId}:${topic.id}`,profileId:activeProfileId,topicId:topic.id,viewedSections:[],manualReview:false,status:correct/total<0.5?'needs-review':'studying',masteryScore:0,updatedAt:now});notifyDataChanged()}};return <><Link className="back-link" to={`/topics/${topic.id}`}><ArrowLeft size={17}/> К теме {topic.code}</Link><header className="page-header"><div><p className="eyebrow">Мини-тест · тема {topic.code}</p><h1>Проверьте ключевые понятия</h1><p>{topic.originalText}</p></div></header><section className="quiz-card">{topic.quiz.map((question,index)=><div className="quiz-question" key={question.id}><span className="question-number">Вопрос {index+1}</span><QuizQuestionView question={question} answer={answers[question.id]} disabled={Boolean(result)} onChange={(answer)=>setAnswers((current)=>({...current,[question.id]:answer}))}/>{result&&<div className={`answer-feedback ${isAnswerCorrect(question,answers[question.id])?'answer-feedback--correct':'answer-feedback--wrong'}`}>{isAnswerCorrect(question,answers[question.id])?<CheckCircle2/>:<XCircle/>}<div><strong>{isAnswerCorrect(question,answers[question.id])?'Верно':'Нужно повторить'}</strong><p>{question.explanation}</p></div></div>}</div>)}{!result?<Button onClick={()=>void submit()} disabled={Object.keys(answers).length<topic.quiz.length}>Проверить ответы</Button>:<div className="quiz-result"><strong>{result.correct} из {result.total}</strong><p>{result.correct===result.total?'Отлично. Закрепите тему ещё одним случайным набором.':'Откройте конспект и повторите пропущенные тезисы.'}</p><div className="button-row"><Button variant="secondary" onClick={()=>{setAnswers(createInitialQuizAnswers(topic.quiz));setResult(null)}}><RotateCcw size={17}/> Ещё раз</Button><LinkButton to={`/practice?topic=${topic.id}`}>Другие вопросы по теме</LinkButton></div></div>}</section></>}
