import { Filter, Search, Shuffle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useProfiles } from '../app/providers/ProfileProvider';
import { topics } from '../content/topics';
import { SECTION_LABELS, type TopicSection } from '../entities/content/topic';
import type { TopicStatus } from '../entities/progress/progress';
import { useMasteryMap } from '../features/progress/useMasteryMap';
import { TopicCard } from '../features/topics/TopicCard';
import { STATUS_LABELS } from '../features/topics/topicStatus';

export function TopicsPage(){const{activeProfileId}=useProfiles();const{map}=useMasteryMap(activeProfileId);const[query,setQuery]=useState('');const[section,setSection]=useState<TopicSection|'all'>('all');const[status,setStatus]=useState<TopicStatus|'all'>('all');const[selected,setSelected]=useState<string[]>([]);const filtered=useMemo(()=>topics.filter((topic)=>{const q=query.trim().toLocaleLowerCase('ru');return(!q||`${topic.code} ${topic.originalText} ${topic.shortAnswer}`.toLocaleLowerCase('ru').includes(q))&&(section==='all'||topic.section===section)&&(status==='all'||(map.get(topic.id)?.status??'not-started')===status)}),[query,section,status,map]);const toggle=(id:string)=>setSelected((items)=>items.includes(id)?items.filter((x)=>x!==id):[...items,id]);return <><header className="page-header"><div><p className="eyebrow">Свободный выбор</p><h1>Все темы программы</h1><p>43 темы доступны сразу. Фильтры не влияют на порядок изучения.</p></div><div className="counter-pill">{filtered.length} из 43</div></header><section className="filters" aria-label="Фильтры каталога"><label className="search-field"><Search size={18}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Поиск по номеру или формулировке"/></label><label><Filter size={16}/><select value={section} onChange={(e)=>setSection(e.target.value as TopicSection|'all')}><option value="all">Все разделы</option>{Object.entries(SECTION_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><select value={status} onChange={(e)=>setStatus(e.target.value as TopicStatus|'all')}><option value="all">Все статусы</option>{Object.entries(STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></section>{selected.length>0&&<div className="selection-bar"><span>Выбрано тем: <strong>{selected.length}</strong></span><Link className="button button--primary" to={`/practice?topics=${selected.join(',')}`}><Shuffle size={17}/> Тренировать выбранные темы</Link><button className="button button--ghost" onClick={()=>setSelected([])}>Сбросить</button></div>}<div className="topic-grid topic-grid--catalog">{filtered.map((topic)=><TopicCard key={topic.id} topic={topic} mastery={map.get(topic.id)} selected={selected.includes(topic.id)} onSelect={toggle}/>)}</div>{filtered.length===0&&<div className="empty-state"><h2>Ничего не найдено</h2><p>Измените запрос или снимите часть фильтров.</p></div>}</>}
